spring.application.name=deepseek-java-project
#Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db
spring.datasource.username=self_fu
spring.datasource.password=self_fu

#Hibernate
#spring.jpa.hibernate.ddl-auto=spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true